---
extends: relaxed

rules:
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]

ignore:
  - netbox-docker/
  - platform/services/netbox/deployment/netbox-docker/
  - .github/
